export default function () {
    return [
        {
            id: 0,
            title: 'Sensen Kekkei',
            about: 'Frontend + Backend',
            content: 'Créer votre application WEB rapidement avec un environnement riche déjà monté ',
            thumb: 'assets/images/logo/sensen-logo-kekkei.png',
            mediaType: '-image',
            mediaURL: '',
            categories: undefined,
            created: '2022-04-14 00:00:00',
            updated: undefined,
            avail: true,
        },
        {
            id: 1,
            title: 'Sensen Katon',
            about: 'Frontend',
            content: 'Créer votre application WEB rapidement avec un environnement riche déjà monté ',
            thumb: 'assets/images/logo/sensen-logo-katon.png',
            mediaType: '-image',
            mediaURL: '',
            categories: undefined,
            created: '2022-04-14 00:00:00',
            updated: undefined,
            avail: true,
        },
        {
            id: 2,
            title: 'Sensen Futon',
            about: 'Backend',
            content: 'Créer votre application WEB rapidement avec un environnement riche déjà monté ',
            thumb: 'assets/images/logo/sensen-logo-futon.png',
            mediaType: '-image',
            mediaURL: '',
            categories: undefined,
            created: '2022-04-14 00:00:00',
            updated: undefined,
            avail: true,
        },
    ];
}
